.dockerignore, Dockerfile, nginx.conf
See individual commits for details but the TL;DR version is:
* Don't use node_modules from host at all
* Use nginx.conf to disable caching of index.html
=> Improve deployment consistency

README.md, package.json, src/utils/install-monaco.js
Running `cpx` works differently on window and linux (globing and quoting issues). This adds a tiny helper that does the required work in code rather than command line commands.
I am not able to confirm it is working correctly on linux so not merging yet.
=> fix the monaco install problem on windows

README.md, package-lock.json, package.json, src/actions/packageActions.js, src/actions/ui.js, src/api/clearlyDefined.js, src/components/ComponentList.js, src/components/FilterBar.js, src/components/GitHubCommitPicker.js, src/components/GitHubSelector.js, src/components/InfiniteList.js, src/components/NpmVersionPicker.js, src/components/PageComponentDetails.js, src/components/PageComponents.js, src/components/RehydrationProvider.js, src/components/RowEntityList.js, src/components/TwoLineEntry.js, src/components/index.js, src/reducers/index.js, src/reducers/packageReducer.js, src/reducers/tableReducer.js, src/reducers/uiReducer.js, src/styles/_List.scss, src/utils/install-monaco.js, src/utils/routingConstants.js
The current component definition browsing is very detailed. It is hard to get a big picture of what's going on . This PR introduces a list much like the harvest queue list but with expandable panels for more details on each component. the idea is that you can have a whole set of components and see the overview and then click to get a bit more and then click Inspect (or some such) to get the full detail.
Along the way we added some new concepts and implementation
* row list with expandable panel -- This is an enhancement to `RowEntityList` where each entry has an optional panel below that can optioanlly be shown.
* API for getting batches of definitions -- needed here and elsewhere, this gets the definitions for a set of components in one go.
* "database" for holding objects -- to manage …
=> Add a new way of browsing component definitions

src/api/clearlyDefined.js
This also supports SERVICE_ENDPOINT if we ever share service configuration.
Tiny change, but hopefully one that'll prevent future toe-stubbing.
=> Default API endpoint to localhost

src/api/clearlyDefined.js, src/components/ComponentList.js, src/components/PageComponents.js, src/components/PageCurate.js, src/components/PageHarvest.js, src/utils/entitySpec.js
Previously we used a harvest request body that looked a lot like that of the crawler. E.g., there was as type and a url , ... that is not particularly natural for CD API users. This PR changes to use tool: and coordinates:, concepts that are natural to CD.
=> use CD structure for harvest request

src/components/PageComponentDetails.js
This resolves #34 
From the /components page, if you select a component from the typeahead search box, then click on the "Dig into this definition" button in the component definition, you will go to /inspect page for that component. From there, if you click either of the two "Add curation" buttons, you will go to the /curate page for that component. 
Note: If no component is selected, the "Add curation" button will be disabled.
Signed-off-by: Max Cohen <cohen@codeaurora.org>
=> Hook up add curation button

package-lock.json, package.json, src/components/ComponentList.js, src/components/CopyUrlButton.js, src/components/PageComponentDetails.js, src/components/PageComponents.js, src/components/PageCurate.js, src/components/PageHarvest.js, src/components/index.js, src/styles/_App.scss, src/styles/_Header.scss, src/styles/_List.scss
This PR:
* Adds a copy-url-button component that leverages `react-copy-to-clipboard`
* Adds the button to components list, inspect, and curate pages (not sure we want them on all, but can easily change)
* A couple UX clean up items (just experimenting, I can revert/change):
* Groups the icon buttons in the component list
* Moves the badge over the left so it doesn't shift the buttons to the left after it renders (this is temporary, long term we can do better)
* Adds bootstrap's "well" styling around the filter boxes
On the Inspect/Curate pages I tried a more subtle "button link" style floated to the right. I didn't want the user to confuse it with a search button (but it looks good as a button and I'm open to changing it or removing altogether):
=> Adds a copy-url-button component

package.json, src/actions/ui.js, src/components/App.js, src/components/NotificationList.js, src/components/PageHarvest.js, src/components/index.js, src/reducers/uiReducer.js
This adds an easy way to trigger notification alerts in the app. It's essentially a container that manages state for the [React Bootstrap Notifier](https://chadly.github.io/react-bs-notifier/). Example: to trigger a notification:
```js
import { uiNotificationNew } from '../actions/ui'
this.props.dispatch(uiNotificationNew({ type: 'info', message: 'Harvesting started.', timeout: 5000 }))
```
For all available options see https://chadly.github.io/react-bs-notifier/ 
To demonstrate usage the Harvest button triggers an "info" alert that harvesting has started. Subsequent PRs can dispatch notifications to the success/error handlers for the harvester.
Fixes #14
=> Add notification alerts

src/components/Landing.js
=> Fix typo on landing page

src/components/ComponentList.js, src/styles/_App.scss, src/styles/_List.scss
The ellipsis overflow rules need to be on a block-level item (`span` is inline). So I just added the class to the `p` which is a block-level item.
Signed-off-by: Mark Matyas <mmatyas@codeaurora.org>
=> Fix text overflow for list items

src/components/ContributePrompt.js
Partially addresses #51 in terms of the styling issues. The template bit can come next. 
* Adds the missing Modal sub components to fix the padding/spacing
* Turns the text input into a textarea (10 rows)
* Adds the close icon in the modal header
* Adds a Cancel button in the form
=> Add Modal sub components to fix styling

src/components/FilterBar.js
Fixes #109 
Not sure why this was there in the first place, so it may break something else. It may have been an attempt at maintaining the filterbar selection after navigating away. #113 should help there.
=> Fix subsequent filtering after first selection

package-lock.json, src/actions/definitionActions.js, src/actions/ui.js, src/api/clearlyDefined.js, src/components/FilterBar.js, src/components/PageCurate.js, src/components/PageDefinitions.js, src/components/PageInspect.js, src/reducers/definitionReducer.js, src/reducers/uiReducer.js
On the service the "list all components" API was not scaling. instead we implemented an explicit "suggest" API for exactly the auto-complete scenario. This PR adapts all uses of getComponentList to use the suggest API.
Note that deployment of this needs to be coupled with the deployment of https://github.com/clearlydefined/service/pull/129 where the new api is added
=> adapt to the new suggest api in service

package-lock.json, src/components/PageDefinitions.js
Implement the feature in #137 .
Note that this should not be merged/used until we address the caching and batching work in #138, #139 and #140. Otherwise we'll DOS shields.io and ourselves.
=> add support for dropping package-lock.json files

src/index.js
Following the [instructions here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#opting-out-of-caching) to disable caching (#99) in the case where the service worker has already been registered.
I'm not able to test this locally, so creating PR so it can be tested. To avoid waiting 24 hours for the cache to be invalidated, you may try the following (in Chrome as an example):
1. Go to https://clearlydefined.io/
2. Open Inspector
3. Right-click the Refresh icon
4. Select **Empty Cache and Hard Reload**
You can follow the above steps if you're in dev mode and leave the existing code as-is. This allows you to see updates immediately and avoid any browser caching.
=> Disable CRA caching

src/api/clearlyDefined.js, src/components/ComponentList.js
Avoid using clearly defined API for badges, instead us shield.io directly.
This relies on https://github.com/clearlydefined/service/pull/170
Fixes: https://github.com/clearlydefined/website/issues/138
=> Use shields.io directly in client

src/components/PageDefinitions.js, src/components/RehydrationProvider.js, src/components/RowEntityList.js, src/reducers/listReducer.js, src/reducers/uiReducer.js
With all the refactoring going on there were a number of compile warnings and runtime errors lingering. This fixes most. Some notes:
* the sort and filter button style should not be an empty string. Causes a runtime error and renders oddly in different environments. I set it to default though that is not the look we want either.
* there are still a number of `componentWillReceiveProps is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead,` We should figure out the right way to do this. We could just use the UNSAFE function but there might be a more generic/modern approach we should use.
=> fix various warnings and errors

src/actions/curationActions.js, src/api/clearlyDefined.js
Edited the handleResponse() function in clearlyDefined.js. So far when the website gets an error it simply receives an error status. Contribution validation; however, sends over both an error status and an error body. Previously the handleResponse() function was not resolving error bodies. Now the handleResponse() function has the ability to resolve error bodies so the can be used.
Each contribution error appears as a UI message notification now as seen in the picture below. The error messages are based on the new error handling that was introduced in service PR [169](https://github.com/clearlydefined/service/pull/169). This is my first attempt at notifying the user that their contribution is incorrect. Any suggestions will be helpful.
=> Validation message

src/api/clearlyDefined.js, src/components/DefinitionEntry.js, src/components/InlineEditor.js
An onChange prop was added as an input to the React.cloneElement. This prop is required for the license picker inline editor; however, causes problems for the date picker inline editor and text inline editor. The onChange prop caused the proxy object itself to trigger and get passed into the onChange function instead of the actual value in the proxy target. Every change should not trigger the onChange function, instead after a user is done editing (onBlur or onKeyPress) the onChange function should be triggered.
=> type based props for inline editor

src/components/PageDefinitions.js, src/reducers/listReducer.js
@Teju-Manchenella did some changes in #232 but the code has been refactored underneath those changes. This ports the changes to make dropping a list of coordinates happen as a batch rather than one at a time.
@daniellandau you might want to take a look as well.
=> port addAll changes to new defintions page

src/components/CopyrightsRenderer.js, src/components/FullDetailView/FullDetailComponent.js, src/components/PopoverRenderer.js
This PR has 3 changes:
1. Implementation of the following solution for #284 :
> Keep the Popover open when editing, so the user MUST click on "Done". Making sure to allow the close the Popover when there are no changes (read-only)
In order to do this, the state of the Copyright values and the functions changing that same state had to be moved from the `PopoverRenderer` to the `CopyRightsRenderer`.
Otherwise when a Copyright item is deleted the PopoverRenderer component will re-render, losing that change.
2. Reverting https://github.com/clearlydefined/website/commit/a77b559a4976a970a043f2e3bd9f90505339c353 (FileList: display all copyrights and highlight the different ones)
If there many Copyrights for a file, this list could be very long and this change was not part of #278 
3. Small UX …
=> Fix #284 - Full Detail View - Editing Copyrights inside the File Edit is confusing

src/utils/contribution.js
=> Issue #329 - "Pencil" icon for selecting declared license redirects you to a blank page when clicked

src/api/clearlyDefined.js, src/components/Navigation/Ui/VersionSelector.js, src/utils/entitySpec.js
@storrisi this is what I meant about the management of origins and entity specs. The UI is trafficking in a plain object, EntitySpec should not know anything about origin URLs and the origin mapping, in the fullness of time, is a combo of type and provider (e.g., we will want to get `releases` from github and git things from gitlab, ...)
=> encasulate version selection origin handling

src/actions/__tests__/definitions.test.js, src/api/clearlyDefined.js, src/components/Navigation/Ui/TitleWithScore.js, src/components/Navigation/Ui/__tests__/ComponentButtons.test.js, src/reducers/__tests__/definition.test.js, src/utils/definition.js
PR https://github.com/clearlydefined/service/pull/291 implements a new scoring algorithm and data structure. This PR updated the website to use the new structure. Basically the returned scores are now a structure with a `total` property (and others). need to get the total rather than just expect the score to be a number.
**Must be merged with https://github.com/clearlydefined/service/pull/291**
=> adapt score rendering to new score structure

src/components/Navigation/Pages/PageBrowse/PageBrowse.js
Change "list of definition that needs" to "list of definitions that need"
=> Fix typo on browse page

src/utils/definition.js
Fixes a bug introduced by https://github.com/clearlydefined/service/pull/323 related to the `_meta` property of the definition schema
=> Fix for change of schema definition

src/components/InlineEditor.js, src/components/Navigation/Sections/HeaderSection.js, src/components/Navigation/Ui/ComponentButtons.js, src/components/Navigation/Ui/ScoreRenderer.js, src/components/Navigation/Ui/TitleWithScore.js, src/components/Navigation/Ui/__tests__/ScoreRenderer.test.js, src/styles/_ScoreRenderer.scss, src/styles/index.scss
This one fixes #385
A tooltip has been added on the Score badge, showing content based on the situation.
When hovering a general score badge:
When hovering a specific score badge:
=> Issue #385 - Add score detail (#58)

src/components/Navigation/Ui/SavePopUp.js
- start the component out with the defaultNoticeTemplate
the same component gets reused for different types, 'file', 'gist', 'notice'
when the type changes the `componentWillReceiveProps` fires. If the type is changing and the new type is notices, default the filename to NOTICE, otherwise clear the value.
We clear the value, because we don't want the NOTICE filename getting saved when you switch to the other types
=> add default notice filename and template

src/actions/definitionActions.js, src/api/clearlyDefined.js, src/components/ComponentList.js, src/components/InfiniteList.js, src/components/Navigation/Pages/PageBrowse/PageBrowse.js, src/components/Navigation/Pages/PageContribution/PageContribution.js, src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js, src/components/SystemManagedList.js, src/reducers/listReducer.js
- rename to browseDefinitions api call to searchDefinitions to be reused
- use isFetching redux pattern for the spinner on browse page
- remove the spinner and threshold override from the infinite scroll
- tighten up the browse window
- remove storeList switches and use the inheritance to change behavior
=> update code for browse page

src/components/DefinitionEntry.js, src/components/FileList/FileList.js, src/components/InlineEditor.js, src/components/LicensesRenderer.js, src/components/SpdxPicker.js, src/styles/_LicenseRenderer.scss
This change will let the user use the inline editor for editing licenses, but launch the license picker if they want to use the expression builder.
=> License picker ui updates

e2e/tests/definitions.js, src/components/Navigation/Ui/__tests__/EditableFieldRenderer.test.js
This fixes a problem when running E2E locally.
Apparently the jest.setTimeout() doesn't work as expected.
Adding back the timeouts to each single test do the trick.
=> E2E: Added back timeouts to test suites

src/components/LicensePicker/RuleBuilder.js, src/components/Navigation/Pages/PageBrowse/PageBrowse.js, src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js, src/components/Navigation/Ui/ComponentButtons.js, src/reducers/uiReducer.js, src/utils/definition.js
There are a few errors and warnings that show up in the browser console when loading the /definitions page. This cleans them up.
=> clean up lint and runtime errors

src/components/FacetsEditor/FacetsEditor.js
The FacetEditor was erroneously referencing a `component` prop when it should have been `definition`
=> switch from component to definition

src/actions/definitionActions.js, src/actions/ui.js, src/reducers/listReducer.js
we were dispatching an update for every definition we got back from the query.
There was also some unused code paths confusing things
=> improve perf of browseDefinitionsAction (fixes #528)

src/components/ContributePrompt.js, src/components/FullDetailView/FullDetailPage.js, src/components/Navigation/Ui/VersionSelector.js, src/components/SourcePicker.js, src/components/SystemManagedList.js
Throughout the UI we should be using OK and Cancel (in that order) but we have a mix. This PR fixes the variations.
Note that for some reason in the SourcePicker I am unable to get the styling to have a space between the two buttons. Not sure what our convention is there and how it is happening elsewhere
=> normalize buttons to OK/Cancel

src/components/PageAbout.js, src/styles/_App.scss
fixes #502 
Pretty much took the `PageLanding` content and moved it to `PageAbout`. Leaving PageLanding for now pending release of the Browse page as the landing page.
=> Move landing page content to About

src/components/Navigation/Pages/PageBrowse/PageBrowse.js, src/components/Navigation/Ui/ComponentButtons.js, src/components/Navigation/Ui/__tests__/ComponentButtons.test.js
Browse page is looking good. Just a couple tweaks
* pull the Curate, Provider and Name inputs to be separate from the list to set a stronger context for the users. Still not fully happy with this. would like to strengthen the Curate messaging so it is clear to users that they can use that to find particular types of things to curate
* removed redundant entry buttons (X and </>) as they cannot be used in the context of the Browse page (system managed list)
=> Tweak Browse page UI

src/components/Navigation/Pages/PageBrowse/PageBrowse.js, src/utils/utils.js
expose the effective score as something to Curate by on the /browse page. This change is instead of #560
=> add "effective" score to Curate button

src/actions/definitionActions.js, src/actions/ui.js, src/components/DefinitionEntry.js, src/components/FullDetailView/FullDetailPage.js, src/components/LicensesRenderer.js, src/components/Navigation/Ui/EditableFieldRenderer.js, src/components/SourcePicker.js, src/components/__tests__/InlineEditor.test.js, src/reducers/index.js, src/reducers/suggestionReducer.js, src/reducers/uiReducer.js, src/utils/withSuggestions.js
`withSuggestions` was storing/getting the suggestion to show in/from one place. that meant that everywhere in the ui that showed a suggestions was showing the same suggestion. Even on different components. This change makes the suggestion redux store a table and puts all the suggestions in there keyed by coordinates. Now once a suggestion is loaded it is available to the correct component anywhere in the UI.
=> fix suggestions redux caching

src/components/Navigation/Ui/ScoreRenderer.js
I noticed this because it was rendering 0 on the badge for a curated component
update to show the effective score
=> update score renderer to use effective score

e2e/maps/definitions.js, e2e/tests/definitions.js, src/components/DefinitionEntry.js
This one fixes some problems that recently caused failures with E2E during the CI
=> Missing component-name in E2E

src/components/HarvestQueueList.js, src/components/TwoLineEntry.js
I've noticed that the previous fix in #597  crashed in the Harvest page since in that page the TwoLineEntry component doesn't receive the full item details.
This PR fix that wrong behavior.
=> Fix Provider icon title in Harvest Page

src/components/SystemManagedList.js, src/components/UserManagedList.js
As noticed in #618 and #614 , the `buildSaveSpec` method needed to be moved to the `SystemManagedList` , since the new home page, which is actually a `SystemManagedList`, is implementing some methods that previously was used only in the `UserManagedList`, like the method above.
Fixes #618 
Fixes #614
=> Moved buildSaveSpec to SystemManagedList

src/components/Navigation/Ui/ListDataRenderer.js
With #596 in place, we noticed that the tooltip shows up only when clicking the Tools or Attributions field, which is not a clear behavior.
We've updated the implementation allow the tooltip to show when hovering the fields.
=> Show Tools and Attributions tooltip/overlay on hover

src/actions/statsActions.js, src/components/Navigation/Pages/PageStats/LicenseBreakdown.js, src/components/Navigation/Pages/PageStats/PageStats.js, src/components/Navigation/Pages/PageStats/TypeCard.js, src/reducers/index.js, src/reducers/statReducer.js
this gets the rest of the stats page working again with a type breakdown
switches from average scores to median scores
includes a license breakdown
=> Stats page updates

src/components/Navigation/Ui/Autocomplete.js
I've found a bug on the new released version of typeahead in the LicensePicker.
This will fix that small problem.
=> Typeahead Bugfix

package-lock.json, src/components/Header.js, src/components/RehydrationProvider.js, src/components/SpdxPicker.js, src/reducers/index.js, src/reducers/navigationReducer.js, src/reducers/uiReducer.js
As discussed with @dabutvin , we need to separate the `navigation` reducer from the others, for 2 reasons:
1. We don't need to persist the `navigation`, the user wouldn't see any change in the menu since the information would be stored in the localStorage
2. Logically, the `navigation` is not a useful information for the workflow of the user, so we can store it in a separate reducer.
I've also added a transform function to the `ui` persistance, in order to store only the `definitions` portion.
This would allow everyone to see this change, otherwise they will continue to take the navigation data from the storage.
=> Separate navigationReducer from uiReducer

src/components/LicensePicker/utils.js, src/components/Navigation/Pages/PageBrowse/PageBrowse.js, src/components/Navigation/Sections/FilterBar.js, src/components/SystemManagedList.js, src/utils/utils.js
This is the idea:
- NOASSERTION is a machine only term
- curations can choose from NONE / OTHER / SPDX
This is meant to short circuit the curation infinite loop.
If you pick up a component that is NOASSERTION, you can mark it as NONE or OTHER and move on
---
=> introduce 'OTHER' as a choice for curating license

src/components/Navigation/Ui/ScoreRenderer.js, src/components/Navigation/Ui/__tests__/ScoreRenderer.test.js, src/styles/_ScoreRenderer.scss
This is related to #652 
This is how the tooltip looks like after the suggested changes:
This implementation still miss one of the suggested changes, about link the titles to a document, that is not yet be written.
=> Score Rendering improvements

src/components/Navigation/Ui/ScoreRenderer.js
With this fix, each param has as a unit the right total amount as explained by the Scoring Formula document.
=> Fix scoring formula using maxScore for each param

src/components/Navigation/Ui/DefinitionTitle.js, src/styles/_FullDetailComponent.scss
Resolves #752 
Since the definition title could be very long in some cases, the best way is to cut it off at a fixed width, and then show a tooltip over it.
=> Added Tooltip to DefinitionTitle

src/actions/sessionActions.js, src/components/ContributePrompt.js, src/components/FullDetailView/FullDetailPage.js, src/components/Header.js, src/components/SystemManagedList.js, src/reducers/sessionReducer.js, src/utils/auth.js
This follow https://github.com/clearlydefined/service/pull/578 and resolves #778 adding a warning message for all the users that haven't a public email on their GitHub profile.
This will remain a Draft PR until https://github.com/clearlydefined/service/pull/578 would not be merged on the service.
=> Warning message for users without a public email

src/components/FullDetailView/FullDetailComponent.js, src/components/Navigation/Sections/HeaderSection.js, src/components/Navigation/Ui/HarvestIndicator.js, src/styles/_FullDetailComponent.scss
Resolves #742 
Adding an Harvest Status Indicator to the Full Detail Page, i've also changed a little bit the view of the section in order to give some space to all the indicators.
Now the heading section looks like this:
=> Adding harvest indicator on full detail page

src/components/Navigation/Pages/PageStats/PageStats.js
I've modified Debian stats in order to check for `deb` param.
I've also added a card for `debsrc`, but the call to the service fails:
Fixes #836
=> Add deb and debsrc stats

src/components/Navigation/Pages/PageStats/LicenseBreakdown.js, src/components/Navigation/Pages/PageStats/PageStats.js
PageStats component now properly dispatches the uiNavigation message
In addition several React errors were fixed in...
1. PageStats
- TypeCard given an unique "key" prop.
- Tabs require an id for accessibility
- Tab given an unique "key" prop.
2. LicenseBreakdown
- XAxis
+ tickSize data type changed to integer (from boolean)
+ dy properly set to JSX integer expression (from string)
- Cell given an unique "key" prop.
Signed-off-by: Tom Marble <tmarble@info9.net>
=> Fixes Stats active status in the navigation bar

src/reducers/navigationReducer.js
I was troubleshooting another bug and noticed the views related to Harvesting, which I had no way of seeing or knowing that they exist. This is because it only showed in the nav bar for users who had the harvest permission. However, even though the option in the nav bar was hidden, anyone could visit https://clearlydefined.io/harvest and kick off a harvest. Additionally, anytime someone visits the definitions page for a component (for example, https://clearlydefined.io/definitions/npm/npmjs/-/split.js/1.6.3) and that component has not been harvested, a harvest is automatically queued. 
There doesn't seem to be a compelling reason to lock down the Harvest option in the nav bar. Additionally, having it visible ensures that we are aware of it and remember that it exists.
Signed-off-by: Nell …
=> shows harvest option in the nav bar to everyone

src/components/Footer.js
Evolving the footer for the website, "ClearlyDefined is an OSI incubator project, originally contributed with ❤️ by Microsoft and maintained by a growing community"
=> Footer: updating wording and linking to OSI

src/components/Providers/Selectors/CocoaPodsSelector.js, src/components/Providers/Selectors/ComposerSelector.js, src/components/Providers/Selectors/CrateSelector.js, src/components/Providers/Selectors/GitHubSelector.js, src/components/Providers/Selectors/MavenSelector.js, src/components/Providers/Selectors/NpmSelector.js, src/components/Providers/Selectors/NuGetSelector.js, src/components/Providers/Selectors/PyPiSelector.js, src/components/Providers/Selectors/RubyGemsSelector.js, src/components/Providers/VersionPickers/CocoaPodsVersionPicker.js, src/components/Providers/VersionPickers/ComposerVersionPicker.js, src/components/Providers/VersionPickers/CrateVersionPicker.js, src/components/Providers/VersionPickers/GitHubCommitPicker.js, src/components/Providers/VersionPickers/MavenVersionPicker.js, src/components/Providers/VersionPickers/NpmVersionPicker.js, src/components/Providers/VersionPickers/NuGetVersionPicker.js, src/components/Providers/VersionPickers/PyPiVersionPicker.js, src/components/Providers/VersionPickers/RubyGemsVersionPicker.js, src/components/index.js
To be consistent with DebianSelector and DebianVersionPicker
Test cases:
-tested package searching for all affected providers in the harvest page. (During testing, found an issue with crate.io search, tracked as https://github.com/clearlydefined/service/issues/938)
-SourcePicker (using GitHubSelector and GitHubCommitPicker) is also tested via definition page
(http://localhost:3000/definitions/pod/cocoapods/-/SoftButton/0.1.0) by editting Described.Source.
=> Moved package selectors and version pickers

src/components/Navigation/Pages/PageBrowse/PageBrowse.js
1. Added provider to the pattern string for coordinates suggestion
The search api call in service ignores provider type.
For example, the following call return co-ordinates with provider other than npmjs:
curl -X GET "https://dev-api.clearlydefined.io/definitions?pattern=jw&type=npm" -H "accept: */*"
This is probably by design: the suggestion api only takes the pattern
string into account.
When provider is included in the pattern string, the search result
reflects the provider specification. The solution is to pass the
provider information when searching in PageBrowse.
2. Also trigger search when provider is changed
Task: https://github.com/clearlydefined/website/issues/957
=> Support component search by provider

src/components/ComponentList.js, src/styles/_App.scss, src/styles/_List.scss, src/styles/style.css
1. The height on the clearly-table-body crops the scroll bar, so
scrolling cannot reach the item at the end of the list.  Moved the
height styling to address this.
2. There is a blank space after components in the table even when
there is not enough space to display all the components.  This is
because renderFilterBar, passed as props from the container components
(e.g. PageDefinition), is not called in ComponentList.  Padding to
accommodate the FilterBar is added by the parent of the ComponentList,
thus leaving a blank space after the ComponentList when FilterBar is
not rendered inside ComponentList.
Change the spacing from padding in the section (parent) to margin of
the ComponentList (child), where showing filter bar is determined.
Also add the conditional formatting to control the …
=> Fix scrolling in ComponentList

src/actions/definitionActions.js, src/components/FullDetailView/AbstractFullDetailsView.js, src/components/FullDetailView/FullDetailComponent.js, src/components/FullDetailView/FullDetailPage.js, src/components/Navigation/Pages/PageBrowse/PageBrowse.js, src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js, src/components/Navigation/Ui/ComponentButtons.js, src/components/Navigation/Ui/VersionSelector.js, src/components/SystemManagedList.js, src/styles/_Popover.scss, src/styles/_VersionSelector.scss, src/styles/index.scss
This is to address some of the issues tracked in https://github.com/clearlydefined/website/issues/946.
-Viewing components (Inspect) is supported in workspace and curation.
-Adding source component, switching to other version, and adding more versions are now supported in workspace.
-Deleting component is also enabled in workspace
=> Fix and enhance component buttons

.github/workflows/test.yml
To complete the switch to GitHub Actions across crawler, service, and website, this adds the same GitHub Actions workflow file that's already running in the other two repos on every pull request.
Once this is merged and verified, I'll follow up with removing the Azure Pipelines config.
=> Add GitHub Actions workflow file to run CI

src/components/Footer.js
Change the footer description, as ClearlyDefined is not an incubator project anymore. We can add reference to Microsoft's donation of the project in the documentation.
=> docs: change footer

.github/workflows/build-and-deploy-dev.yml
Fixes #1057 
----
The v2.0.0 deploy workflows support passing docker build args to the docker build.  This fixes the problem where the `REACT_APP_SERVER` arg to docker was not set.  This was causing the website to communicate with the service at localhost:4000 instead of the expected dev.clearlydefined.io.  The change also adds a new job to upload the package-lock.json file to the build artifacts.  This is needed for the build-and-deploy job to be able to get the version from that file.
* https://github.com/clearlydefined/operations/pull/86
* https://github.com/clearlydefined/service/pull/1154
=> use v2.0.0 deploy & pass docker build args

.github/workflows/build-and-deploy-dev.yml
Build args that are in quotes have the quotes encoded leading to an incorrect value when the Docker image is built.  This removes the quotes.  The dev website was confirmed to load correctly after this change.
=> Remove quotes from all docker build-args

.github/workflows/build-and-deploy-dev.yml, Dockerfile, default.conf.template, nginx.conf
Adds a health endpoint which returns app version and sha.
```
{"status":"OK", "version": "2.2.1", "sha": "12345"}
```
Endpoint has been implemented via nginx.
As the site is a React page the alternative would have been adding a Node.js endpoint the app would need to expose.
Using nginx is a lot less complex and easier to maintain in the future
Deployed to development and it's working:
```
curl https://dev.clearlydefined.io/health
=> {"status":"OK", "version": "v0.1.1-dev-654d7fca75", "sha": "654d7fca7516735b2e9891b8657352cf3b3e0a4e"}
```
=> Add health endpoint via nginx
