- src/api/clearlyDefined.js
- src/components/ComponentList.js
- src/components/CurationReview.js
- src/components/FilterBar.js
- src/components/PageComponentDetails.js
- src/components/PageComponents.js
- src/components/PageCurate.js
- src/reducers/definitionReducer.js
- src/reducers/listReducer.js
- src/reducers/tableReducer.js
- src/styles/_List.scss
- src/utils/entitySpec.js
* add releaseDate, file counts, ... to the panels
* add inspect and curate buttons on each entry
* add an _Add source_ button that adds a package's corresponding source (if any) to the browse list
* various fixes to little nits
> Add more data to the browse page

- package-lock.json
- package.json
- src/components/ComponentList.js
present move of the accumulated data including the `declared` license
> update schema for attribution and declared

- src/components/Clearly.js
- src/components/ComponentList.js
- src/components/Landing.js
- src/components/index.js
- src/styles/_App.scss
Just trying out some words and tone for the landing page...
* needs a blurb or something very short at the top to intro ClearlyDefined.
* talk more about upstreaming ideas in the Get ClearlyDefined section
* connect up the Learn more links
> first cut at content for the landing page

- src/components/PageComponents.js
Signed-off-by: Craig Northway <cnorthway@codeaurora.org>
> Remove source filter action buttons from page

- src/components/PageAbout.js
Added About page text and Partners section with logos. We may need some padding on the table of Partners.
Resolves #11
> Add About text and Partners section

- .prettierrc
- public/index.html
- src/components/Clearly.js
- src/components/Footer.js
- src/components/Landing.js
- src/components/PageAbout.js
- src/components/SocialIcons.js
- src/images/partner-logos/partner-list.md
- src/styles/_App.scss
- src/styles/_Footer.scss
- src/styles/_variables.scss
* update the footers
* change social media bits
* tweak about wording
* normalize colors
> A series of formatting and other changes

- src/components/ContributePrompt.js
- src/components/CurationReview.js
- src/components/PageCurate.js
- src/components/PageInspect.js
- src/components/index.js
Connect up the propose button, handle contribute saving when there is nothing to save, ...
Also some internal renaming to make things more consistent
> round out curate flows

- src/styles/_List.scss
Fixes #89
Signed-off-by: Mark Matyas <mmatyas@codeaurora.org>
> Fix license position in component list

- src/components/PageLanding.js
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> corrects minor typo

- package-lock.json
- package.json
- public/index.html
- src/components/ComponentList.js
- src/components/CopyUrlButton.js
- src/components/HarvestQueueList.js
- src/components/PageAbout.js
- src/components/PageLanding.js
- src/components/SocialIcons.js
Fixes #86 
Went the React-less route since it doesn't require explicit icon importing. Not much work to switch back if we want.
> Move to Font Awesome 5

- nginx.conf
> support HTML5 pushstate

- src/components/FilterBar.js
These couple of updates seemed to be sufficient. Fixes #35 
Signed-off-by: Mark Matyas <mmatyas@codeaurora.org>
> Remember selection in FilterBar

- src/components/PageCurate.js
- src/components/PageInspect.js
Simliar to curate page, fill in filterbar w/ path
> Simliar to curate page, fill in filterbar w/ path

- package-lock.json
- package.json
- src/actions/curationActions.js
- src/components/ComponentList.js
- src/components/DefinitionEntry.js
- src/components/InlineEditor.js
- src/components/PageDefinitions.js
- src/components/RehydrationProvider.js
- src/reducers/listReducer.js
- src/reducers/uiReducer.js
- src/styles/_App.scss
- src/utils/entitySpec.js
Added save functionality and ui tweaks.
> Save button

- src/components/DefinitionEntry.js
Fix the releaseDate format to be schema compliant
> update releaseDate format

- src/components/ComponentList.js
- src/components/PageDefinitions.js
- src/components/Section.js
- src/reducers/listReducer.js
Added collapse all button that collapses all the expanded components.
> Collapse all

- src/components/FacetsRenderer.js
- src/components/FileList/FileList.js
This implementation fixes #238
> Added "Core" default to Facets Rendering

- src/components/AbstractPageDefinitions.js
> added score to sorting

- src/components/FullDetailView/FullDetailComponent.js
Fix for: https://github.com/clearlydefined/website/issues/244
Now:
> fix missing fields on FullDetailPage #244

- src/components/FullDetailView/FullDetailComponent.js
- src/components/FullDetailView/FullDetailPage.js
> Fixed FullDetails commit string if sourceLocation is not available

- src/components/FacetsEditor/FacetsEditor.js
- src/components/FacetsRenderer.js
- src/components/GlobsPicker.js
- src/styles/_FacetsEditor.scss
* updated FacetsRenderer using tags
* added GlobsPicker using tags
* updated FacetsEditor using GlobsPicker rather than InlineEditor
> Updated Facets and Globs rendering in Full Details View using ant-design tags

- package-lock.json
- package.json
- src/components/CopyrightsRenderer.js
> Added `container` prop on OverlayTrigger on CopyrightsRenderer

- src/components/CopyrightsRenderer.js
- src/components/FileList/FileList.js
- src/components/PopoverRenderer.js
> Fix Licenses and Copyrights filters on Full Details View

- src/api/clearlyDefined.js
- src/components/ComponentList.js
- src/components/DefinitionEntry.js
- src/components/FacetsEditor/FacetsEditor.js
- src/components/FullDetailView/FullDetailComponent.js
- src/components/PageContribution.js
- src/styles/_FullDetailComponent.scss
- src/utils/definition.js
- src/utils/entitySpec.js
* remove some buttons and data from the Definitions list entries
* restructure the Full details view a bit
* update the scoring display on Definitions and full details
> Various UI tweaks 

- src/components/CopyrightsRenderer.js
- src/components/FacetsEditor/FacetsEditor.js
- src/components/InlineEditor.js
- src/components/PageDefinitions.js
- src/styles/_App.scss
- src/styles/_FacetsEditor.scss
Fixes #277 and #278 + minor UI Tweaks.
> Fix Copyrights Edit, Facets Editor and others

- src/components/FileList/FileList.js
>  fix(Full Details View) Filtering doesn't work on edited Licenses

- package-lock.json
- package.json
- src/actions/definitionActions.js
- src/components/PageDefinitions.js
Chunk up the definition fetching by 100, fixes #243
> Issue #243 - Chunk up the definition fetching

- src/actions/definitionActions.js
- src/actions/sessionActions.js
- src/components/AbstractPageDefinitions.js
- src/components/ContributePrompt.js
- src/components/FieldGroup.js
- src/components/FullDetailView/FullDetailPage.js
- src/components/Header.js
- src/components/PageContribution.js
- src/components/PageCurate.js
- src/components/PageDefinitions.js
- src/reducers/sessionReducer.js
- src/styles/_App.scss
- src/utils/auth.js
Fixes #282 
This needs to be merged together with clearlydefined/service PR [#236](https://github.com/clearlydefined/service/pull/236)
> Issue #282 (CI) - Enhance contribution/PR descriptions

- src/components/DefinitionEntry.js
- src/styles/_App.scss
> Issue #293 - Copyright Attribution and Discovered Licensed not being highlighted

- src/components/PageDefinitions.js
> Issue #136 - constrain the type of files that can be dropped

- src/actions/definitionActions.js
- src/actions/ui.js
- src/components/AbstractPageDefinitions.js
- src/components/ComponentList.js
- src/components/DefinitionEntry.js
- src/components/FacetsEditor/FacetsEditor.js
- src/components/FullDetailView/FullDetailComponent.js
- src/components/FullDetailView/FullDetailPage.js
- src/components/GlobsPicker.js
- src/components/InlineEditor.js
- src/components/LicensesRenderer.js
- src/components/NotificationButtons/NotificationButtons.js
- src/components/NotificationButtons/index.js
- src/components/PageDefinitions.js
- src/components/PopoverRenderer.js
- src/components/Section.js
- src/reducers/listReducer.js
- src/styles/_App.scss
- src/utils/definition.js
> Issue #197 - Revert individual or all changes to contributions made

- src/styles/_Popover.scss
> Issue #314 - Fix field style to avoid long texts

- src/components/ComponentList.js
- src/components/DefinitionEntry.js
- src/components/TwoLineEntry.js
- src/styles/_List.scss
- src/utils/definition.js
Fixes #162 , completing the outstanding implementation for that issue
> Issue #162 - High level view of definition (icon and empty component)

- src/components/ComponentList.js
> Adding Back CopyUrl Button in ComponentList

- package-lock.json
- package.json
- src/components/PageDefinitions.js
- src/utils/entitySpec.js
> Issue #183 - DnD URLs from all supported providers

- package-lock.json
- package.json
- src/actions/__tests__/definitions.test.js
- src/actions/__tests__/ui.test.js
- src/actions/curationActions.js
- src/api/clearlyDefined.js
- src/components/DefinitionEntry.js
- src/components/Navigation/Ui/__tests__/ButtonWithTooltip.test.js
- src/components/Navigation/Ui/__tests__/CurationData.test.js
- src/components/PageDefinitions.js
- src/components/SocialIcons.js
- src/components/__tests__/PageDefinitions.test.js
- src/reducers/__tests__/definition.test.js
- src/utils/__tests__/definition.test.js
Related to issue #24 
* Updated react-scripts to 2.0.4
* Added some samples, and actually working, tests implementation of components, utils, actions, async actions using fetch-mock, reducer tests and connected components
* Proposal of scaffolding method for __tests__ folders
> Tests Implementation

- src/components/AbstractPageDefinitions.js
- src/components/PageDefinitions.js
> Issue #188 - Export list to a named file

- src/components/AbstractPageDefinitions.js
This fix an error thrown by the implementation of the save file PopUp.
> Fix renderPopup error

- src/components/SpdxPicker.js
- src/utils/utils.js
> Display SPDX Licences NONE and NOASSERTION options in License Picker

- src/components/GitHubCommitPicker.js
- src/components/HarvestQueueList.js
- src/components/MavenVersionPicker.js
- src/components/NpmVersionPicker.js
- src/components/NuGetVersionPicker.js
- src/components/PyPiVersionPicker.js
- src/components/RubyGemsVersionPicker.js
> Issue #214 - harvesting form shows wrong tags when deleting request

- src/api/clearlyDefined.js
- src/components/Navigation/Ui/VersionSelector.js
- src/components/__tests__/entitySpec.test.js
- src/utils/entitySpec.js
These tests are modeled after the ones from @storrisi  in #356 and will supersede those.
> Add tests for entity spec

- src/components/AbstractPageDefinitions.js
- src/components/FullDetailView/FullDetailPage.js
- src/components/GitHubCommitPicker.js
- src/components/Navigation/Ui/ButtonWithTooltip.js
- src/components/Navigation/Ui/ComponentButtons.js
- src/components/Navigation/Ui/VersionSelector.js
fixing lint issues
will proactively merge
> fix lint errors

- src/api/clearlyDefined.js
- src/api/github.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/Navigation/Ui/ComponentButtons.js
- src/components/Navigation/Ui/DropComponent.js
- src/components/Navigation/Ui/ShareButton.js
- src/components/SystemManagedList.js
- src/components/UserManagedList.js
@storrisi @AlexWebYourmind Please validate these fixes.
> various updates for integration errors

- src/styles/_App.scss
> Issue #392 - Fix Contribution modal style

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Pages/PageContribution/PageContribution.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/SystemManagedList.js
> Issue #389 - Added specific store management method

- src/components/CopyUrlButton.js
- src/components/Navigation/Ui/ButtonWithTooltip.js
- src/components/Navigation/Ui/__tests__/ButtonWithTooltip.test.js
- src/styles/_App.scss
> Tooltips over disabled buttons

- src/components/Navigation/Ui/EditableFieldRenderer.js
- src/components/Navigation/Ui/__tests__/CurationData.test.js
- src/components/Navigation/Ui/__tests__/CurationRenderer.test.js
- src/components/Navigation/Ui/__tests__/DropComponent.test.js
- src/components/Navigation/Ui/__tests__/EditableFieldRenderer.test.js
This is a work in progress PR that address the implementation of tests for most of the components and methods of the Website Application.
> WIP - Tests coverage

- src/components/SourcePicker.js
> Issue #347 - Open source links in a new page

- src/components/Navigation/Ui/ScoreRenderer.js
- src/styles/_ScoreRenderer.scss
Make the score elements yellow or red depending on how far off their full score they are.
> highlight problem score elements

- src/utils/utils.js
> Issue #410 - Removed NOASSERTION value from SpdxPicker

- src/components/Navigation/Pages/PageBrowse/__tests__/ButtonsBar.test.js
- src/components/Navigation/Pages/PageContribution/__tests__/ButtonsBar.test.js
- src/components/Navigation/Pages/PageDefinitions/ButtonsBar.js
- src/components/Navigation/Pages/PageDefinitions/__tests__/ButtonsBar.test.js
- src/components/Navigation/Sections/ButtonsBar.js
- src/components/Navigation/Ui/ShareButton.js
Fixes #445 
While working on this i've also increased the tests coverage of the ButtonsBar component.
> Issue #445 - Clear All button never enabled

- src/components/ModalEditor.js
- src/components/Navigation/Sections/LicensedSections.js
- src/components/Navigation/Sections/TwoColumnsSection.js
- src/components/Navigation/Ui/EditableFieldRenderer.js
- src/components/Navigation/Ui/Suggestions/SuggestionRenderer.js
- src/components/Navigation/Ui/__tests__/EditableFieldRenderer.test.js
- src/styles/_App.scss
- src/styles/_List.scss
Now that the Suggestions are in place, i was able to test the behavior on the UI, and i found some issues with the ModalEditor that i fixed in this PR.
To test how the Suggestions works, you can check https://dev.clearlydefined.io//definitions/nuget/nuget/-/Newtonsoft.Json/10.0.2
> Suggestions rendering fixes

- .vscode/launch.json
- src/actions/definitionActions.js
- src/actions/ui.js
- src/api/clearlyDefined.js
- src/components/ComponentList.js
- src/components/InfiniteList.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/Navigation/Sections/FilterBar.js
- src/components/RowEntityList.js
- src/components/SystemManagedList.js
- src/components/UserManagedList.js
- src/components/__tests__/PageDefinitions.test.js
- src/reducers/listReducer.js
- src/reducers/uiReducer.js
- src/utils/utils.js
Now the page calls the endpoint with filters attached to the query.
`continuationToken` has been added to manage pagination as well.
FilterBar has been improved in order to accept custom values for each of the shown filters.
> Browse page improvements

- src/components/DefinitionEntry.js
- src/utils/entitySpec.js
> Update link for github components

- src/actions/definitionActions.js
- src/components/DefinitionEntry.js
- src/components/LicensesRenderer.js
> Issue #470 - Revert action doesn't work on Definitions List

- src/components/TwoLineEntry.js
> Issue #332 - Maven favicon doesn't light up when you've made a curatio

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
> Browse: sort provider names

- src/styles/_FullDetailComponent.scss
> hide the blue border

- src/components/ContributePrompt.js
- src/styles/_App.scss
- src/styles/_bootstrapFixes.scss
> Issue #482 - Add guidance on popup for curation submission

- src/styles/_FacetsEditor.scss
> Issue #476 - Fix Facets background color when edited

- e2e/maps/fulldetailsview.js
- e2e/tests/fulldetailsview.js
Since the new Filelist has been merged, some e2e tests error showed up.
This one will fix those errors.
> Fix Filelist e2e

- src/utils/filelist.js
> return empty if there are not files

- src/components/Navigation/Ui/ListDataRenderer.js
came across this looking at https://github.com/clearlydefined/crawler/issues/148
> change item propType to string

- src/api/clearlyDefined.js
- src/components/ComponentList.js
- src/components/DefinitionEntry.js
- src/components/Navigation/Sections/HeaderSection.js
- src/components/Navigation/Ui/ComponentButtons.js
- src/components/Navigation/Ui/CurationRenderer.js
- src/components/Navigation/Ui/ScoreRenderer.js
- src/components/Navigation/Ui/__tests__/CurationRenderer.test.js
- src/styles/_App.scss
- src/styles/_List.scss
- src/styles/_bootstrapFixes.scss
> update the look of the definition list

- src/components/Header.js
> Header: fix Logout and Docs positions

- src/components/Navigation/Pages/PageBrowse/ButtonsBar.js
- src/components/Navigation/Pages/PageDefinitions/ButtonsBar.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/Navigation/Pages/PageDefinitions/__tests__/ButtonsBar.test.js
- src/components/Navigation/Sections/ButtonsBar.js
- src/components/Navigation/Ui/SavePopUp.js
- src/components/Navigation/Ui/ShareButton.js
> Remove Gist option from Share dropdown

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
Fixes #500 
@jeffmcaffer what do you think?
> Move Provider and Curate buttons near the name search field

- src/components/FilterBar.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Ui/SearchBar.js
- src/components/__tests__/PageBrowe.test.js
- src/utils/entitySpec.js
> Browse Page: update name search box to use typeahead

- e2e/maps/browse.js
- e2e/maps/definitions.js
- e2e/tests/definitions.js
- e2e/tests/revertBrowsedDefinitions.js
- e2e/tests/revertDefinition.js
- src/actions/definitionActions.js
- src/actions/ui.js
- src/components/FullDetailView/FullDetailPage.js
- src/components/Navigation/Pages/PageBrowse/ButtonsBar.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Pages/PageDefinitions/ButtonsBar.js
- src/components/Navigation/Ui/NotificationButtons.js
- src/components/SystemManagedList.js
Updated revert method to work with both definition and browse store
Fixes #542
> Issue #542 - Browse Page: revert function doesn't work as expected

- src/components/App.js
- src/components/ComponentList.js
- src/components/HarvestQueueList.js
- src/components/InfiniteList.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Pages/PageContribution/PageContribution.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/PageHarvest.js
- src/components/RowEntityList.js
- src/components/Section.js
- src/styles/_App.scss
- src/styles/_List.scss
- src/styles/_variables.scss
- src/utils/utils.js
> Browse: Make list height relative to height of window

- src/components/FileList/FileList.js
- src/components/FullDetailView/FullDetailComponent.js
- src/styles/_FullDetailComponent.scss
> Tweak new File List view

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
Fixes #495 
Needs clearlydefined/service#439 to be merged first.
> Browse: Sort by score should use effective and tool 

- src/components/LicensePicker/style.css
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
Some of the recent merge has introduced a layout issue in the Browse Page.
This PR fix that problem.
> Tweak layout fixes

- e2e/maps/browse.js
- src/components/LicensePicker/style.css
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/SpdxPicker.js
> Added SpdxPicker in Browse Page filters

- src/components/DefinitionEntry.js
- src/components/FilterBar.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Ui/FilterList.js
- src/styles/_FilterCustomComponent.scss
Do some more styling on the /browse page buttons at the top
> style the browse page buttons

- src/index.js
- src/utils/withTracker.js
As part of #540 , a check has been introduced to avoid ReactGA to run locally, causing warnings on the console.
> Added to check to avoid ReactGA run locally

- src/components/PageHarvest.js
- src/styles/_App.scss
> Curation component list too short

- src/components/FileList/FileList.js
> Fixed state of FileList when mounting

- src/utils/utils.js
> Added back 'NOASSERTION' to LicensePicker values

- src/components/FullDetailView/FullDetailComponent.js
At least make the raw data section the same width as the rest...
> change width of raw data

- src/components/TwoLineEntry.js
> Added alt and title attribute to definition icons

- src/api/clearlyDefined.js
- src/components/FullDetailView/FullDetailPage.js
- src/utils/entitySpec.js
> Retrieve harvested data without PR value

- src/components/DefinitionEntry.js
- src/components/Navigation/Sections/HeaderSection.js
- src/components/SystemManagedList.js
- src/utils/definition.js
> Removed computedScore() method from the UI

- src/components/Navigation/Sections/DescribedSection.js
- src/components/Navigation/Ui/EditableFieldRenderer.js
- src/components/Navigation/Ui/ListDataRenderer.js
> Use ListDataRenderer to display a long list of tools

- src/actions/definitionActions.js
- src/api/clearlyDefined.js
- src/components/ComponentList.js
- src/components/Navigation/Ui/ComponentButtons.js
- src/components/Navigation/Ui/DropComponent.js
- src/components/SystemManagedList.js
- src/components/UserManagedList.js
- src/utils/contribution.js
- src/utils/definition.js
- src/utils/entitySpec.js
- src/utils/withSuggestions.js
the name change done in #607 was less than optimal. Here a set of names are updated to be (hopefully) more consistent.
> update EntitySpec conversion/trimming names

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Sections/ActiveFilters.js
- src/styles/_App.scss
- src/utils/utils.js
> Show selected value in browse page buttons

- src/components/Navigation/Sections/HeaderSection.js
- src/styles/_bootstrapFixes.scss
> Make button colors consistent across site

- src/styles/_App.scss
> Switch version popup should use montserrat font

- src/components/Navigation/Ui/ScoreRenderer.js
> Score popover text color updates

- src/components/FullDetailView/FullDetailPage.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/styles/_bootstrapFixes.scss
Fixes #628 , changes of colors has already been fixed in #644
> Update UI for 'Unsaved Changes' modal

- src/components/FullDetailView/FullDetailComponent.js
- src/components/Navigation/Sections/HeaderSection.js
> Removed tooltip from Revert button in Full Details view

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
> Added sort by lowest Score after a "Fix something" selection

- src/components/ComponentList.js
- src/components/Footer.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Sections/ActiveFilters.js
- src/components/Navigation/Ui/ComponentButtons.js
- src/styles/_App.scss
- src/styles/_List.scss
- src/styles/_variables.scss
> Homepage UI Updates 

- e2e/tests/revertBrowsedDefinitions.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
> PageBrowse default sort by release date

- src/components/RehydrationProvider.js
> Added ui and definition reducers to redux-persist

- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/utils/utils.js
> Replace search by provider with search by type

- e2e/maps/definitions.js
- package-lock.json
- src/components/FilterBar.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Ui/SearchBar.js
- src/styles/_App.scss
This will work in both Homepage and Workspace:
Fixes #636
> Added logo to definitions search field

- src/components/Navigation/Ui/RawDataRenderer.js
- src/components/Navigation/Ui/__tests__/RawDataRenderer.test.js
> Check for null values on RawDataRenderer

- src/components/FullDetailView/FullDetailComponent.js
> Move facets tooltip near section title

- Dockerfile
git is required as well for the build
> upgrade build to node:10-alpine

- src/components/App.js
- src/components/Navigation/Ui/FullScreenLoader.js
- src/reducers/index.js
- src/reducers/loaderReducer.js
- src/styles/_App.scss
> Added a Loader when loading the details of a definition

- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/Navigation/Sections/FilterBar.js
- src/components/SystemManagedList.js
- src/utils/utils.js
> Added Changes filter to Workspace page

- package-lock.json
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
> Omit continuationToken from Querystring params

- src/components/FileList/FileList.js
- src/components/Navigation/Ui/FullScreenLoader.js
- src/reducers/loaderReducer.js
- src/utils/filelist.js
This resolves #651 and expand the entire file list by default.
BTW, there are some performances issues when playing with a very long list of files.
I will track that problem in another PR.
> Expand files list by default

- package-lock.json
- src/components/ContributePrompt.js
- src/components/FullDetailView/AbstractFullDetailsView.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/SystemManagedList.js
- src/styles/_ContributePrompt.scss
- src/styles/index.scss
This is how the ContributePrompt would look:
Fixes #617
> Showing definition with changes on ContributePrompt

- src/components/LicensePicker/LicensePicker.js
- src/components/LicensesRenderer.js
- src/components/ModalEditor.js
- src/components/Navigation/Sections/LicensedSections.js
- src/utils/EnhancedLicensePicker.js
> Added suggestions to the License Picker modal

- src/components/FullDetailView/AbstractFullDetailsView.js
> Disable Contribute button for non-Harvested components

- src/actions/definitionActions.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/components/SystemManagedList.js
- src/components/UserManagedList.js
- src/reducers/uiReducer.js
> Contribution with Multiselect improvements 

- src/components/CopyUrlButton.js
- src/components/Navigation/Sections/HeaderSection.js
> Added Source button in full detail page

- src/components/CopyUrlButton.js
- src/components/Navigation/Sections/HeaderSection.js
- src/components/Navigation/Ui/ComponentDetailsButtons.js
> Link to other versions of the same components

- src/components/Navigation/Sections/HeaderSection.js
- src/styles/_FullDetailComponent.scss
> Improved styling of header section with longer package names

- src/components/Navigation/Ui/ComponentDetailsButtons.js
> Added link to package URL in full details page

- src/components/DefinitionEntry.js
- src/components/Navigation/Ui/DefinitionRevision.js
- src/styles/_App.scss
> Increased size of revision string

- src/components/FullDetailView/FullDetailComponent.js
- src/components/Navigation/Pages/PageDefinitions/index.js
- src/components/Navigation/Ui/DropComponent.js
- src/components/Navigation/Ui/ScoreRenderer.js
- src/components/Navigation/Ui/__tests__/DropComponent.test.js
- src/components/UserManagedList.js
- src/components/__tests__/PageDefinitions.test.js
- src/utils/utils.js
> Ability to import fossa package files

- src/components/CopyrightsRenderer.js
- src/components/FileList/FileList.js
Resolves #773 
Once deployed, it could be checked using curations/913
> Highlight copyrights on curation change

- src/components/FileList/FileList.js
Resolves #511 
Now shows a checkbox multi-select on License column in the File list
> Boolean filter for Licenses in file list

- package-lock.json
- src/components/SourcePicker.js
> Avoid set null value on source location object

- src/actions/curationActions.js
- src/components/Navigation/Ui/NotificationContent.js
- src/components/NotificationList.js
- src/styles/_App.scss
> Show error code on contribution error notification

- package-lock.json
- src/components/SourcePicker.js
Reverts clearlydefined/website#793
> Revert "Avoid set null value on source location object"

- src/components/FilterBar.js
- src/components/Navigation/Pages/PageBrowse/PageBrowse.js
> Ability to search by namespace in Browse Page

- src/utils/shareUrlDescriptor.proto
> Comment the ShareUrl proto message.

- src/components/DefinitionEntry.js
- src/components/FileList/FileList.js
- src/components/HarvestQueueList.js
- src/components/Navigation/Sections/HeaderSection.js
- src/components/Navigation/Ui/DefinitionRevision.js
- src/components/Navigation/Ui/HarvestIndicator.js
- src/styles/_App.scss
- src/styles/_FullDetailComponent.scss
- src/utils/contribution.js
- src/utils/entitySpec.js
Fixes #813 , Fixes #811 , Fixes #814 , Fixes #815
> FullDetails ui fixes

- src/api/clearlyDefined.js
> Add matchingFalse param for definitions request

- src/components/SystemManagedList.js
- src/components/__tests__/PageDefinitions.test.js
> Use transformedList in components selection

- src/components/FilterBar.js
> Fix FilterBar debian type

- src/utils/entitySpec.js
> Added maven.org domain to URLs check

- src/styles/_LicenseRenderer.scss
- src/styles/_List.scss
> Fix License Renderer style

- src/components/Navigation/Sections/HeaderSection.js
- src/utils/curation.js
> Check for contributions with matching revision number

- src/components/Navigation/Pages/PageStatus/PageStatus.js
> Add chart showing tools ran per day

- README.md
Previous link to https://github.com/clearlydefined/service/readme.md
gives a 404.
Signed-off-by: Tom Marble <tmarble@info9.net>
> Minor fix to README for service/#quick-start

- src/components/FullDetailView/FullDetailComponent.js
- src/utils/curation.js
Improves an equality check: == -> ===
Adjusts JSX comments to use the {/* ... */} convention per
https://wesbos.com/react-jsx-comments/ recommendation
Upon startup one now sees:
```
Compiling...
Compiled successfully!
```
Closes #850
Signed-off-by: Tom Marble <tmarble@info9.net>
> Fixes compilation warnings

- src/components/FullDetailView/FullDetailPage.js
Related to https://github.com/clearlydefined/service/issues/705
> Make sure the right casing is used when a new curation is created

- docs/rampup.md
> adds snyk and dependabot details to ramp up docs

- src/components/FullDetailView/FullDetailComponent.js
> fixes curations raw data tab

- package.json
> updates spdx-license-ids version

- azure-pipelines.yml
> updates azure build to use ubuntu-18.04 now that 16.04 is deprecated

- README.md
> trivial change to test something

- src/components/LicensePicker/LicensePicker.js
- src/components/Navigation/Ui/DefinitionRevision.js
- src/styles/_Popover.scss
Addresses a couple items from issue #931.
> Commit hash now links to repo, fix modal close issue

- package-lock.json
- package.json
- src/components/FilterBar.js
- src/components/GitHubSelector.js
- src/components/Navigation/Pages/PageDefinitions/PageDefinitions.js
- src/reducers/navigationReducer.js
- src/styles/_App.scss
This PR addresses the final blockers from issue #931.
1. Source information modal fix
2. Workspace searchbar fix
3. Adding workspace to navbar
> Final blockers addressed

- src/styles/_FullDetailComponent.scss
Task: https://github.com/clearlydefined/website/issues/962
> Fix "Contribute" window not completely visible

- src/components/FileList/FileList.js
https://github.com/clearlydefined/website/issues/953
> Fix filter values, add onFilter for license filter options

- src/components/Navigation/Sections/HeaderSection.js
> Fixing badge

- src/api/clearlyDefined.js
- src/components/CocoaPodsSelector.js
- src/components/CocoaPodsVersionPicker.js
- src/components/DefinitionEntry.js
- src/components/HarvestQueueList.js
- src/components/Navigation/Pages/PageHarvest/PageHarvest.js
- src/components/index.js
- src/utils/contribution.js
Task: https://github.com/clearlydefined/website/issues/963
> Improve support for cocoapods

- src/components/FileList/FileList.js
- src/styles/_FullDetailComponent.scss
Task: https://github.com/clearlydefined/website/issues/955
> Support license edit

- src/api/clearlyDefined.js
- src/components/CocoaPodsSelector.js
- src/components/CocoaPodsVersionPicker.js
- src/components/DefinitionEntry.js
- src/components/FileList/FileList.js
- src/components/Footer.js
- src/components/HarvestQueueList.js
- src/components/Navigation/Pages/PageHarvest/PageHarvest.js
- src/components/Navigation/Sections/DescribedSection.js
- src/components/Navigation/Ui/ListDataRenderer.js
- src/components/PageAbout.js
- src/components/index.js
- src/styles/_FullDetailComponent.scss
- src/styles/_Popover.scss
- src/utils/contribution.js
Adds the following PR's:
https://github.com/clearlydefined/website/pull/981
https://github.com/clearlydefined/website/pull/980
https://github.com/clearlydefined/website/pull/979
https://github.com/clearlydefined/website/pull/971
https://github.com/clearlydefined/website/pull/969
https://github.com/clearlydefined/website/pull/966
https://github.com/clearlydefined/website/pull/965
https://github.com/clearlydefined/website/pull/960
https://github.com/clearlydefined/website/pull/959
https://github.com/clearlydefined/website/pull/952
> Update prod with latest changes

- src/components/Charter.js
- src/components/Footer.js
- src/components/GetInvolved.js
- src/components/Header.js
- src/components/Navigation/Pages/PageStats/PageStats.js
- src/components/PageAbout.js
Fix broken links in the About page. Fixes #1048
> docs: fix broken links in about page

- .github/workflows/build-and-deploy-dev.yml
Deploy failed because deploy job could not read secret.  Had to read in previous job with steps, save in env, and pass to next job as output.
> have to pull off tracking id in job with steps and pass to next job as output
